apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prom-server:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-service.monitoring.svc.cluster.local:9100']
            labels:
              node: node1
          - targets: ['node-exporter-service.monitoring.svc.cluster.local:9100']
            labels:
              node: node2